// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cox_gradient_at_F
NumericVector cox_gradient_at_F(NumericVector time, IntegerVector event, NumericVector F_scores);
RcppExport SEXP _survivalisttoo_cox_gradient_at_F(SEXP timeSEXP, SEXP eventSEXP, SEXP F_scoresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type time(timeSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type event(eventSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type F_scores(F_scoresSEXP);
    rcpp_result_gen = Rcpp::wrap(cox_gradient_at_F(time, event, F_scores));
    return rcpp_result_gen;
END_RCPP
}
// breslow_F
List breslow_F(NumericVector time, IntegerVector event, NumericVector risk_scores);
RcppExport SEXP _survivalisttoo_breslow_F(SEXP timeSEXP, SEXP eventSEXP, SEXP risk_scoresSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type time(timeSEXP);
    Rcpp::traits::input_parameter< IntegerVector >::type event(eventSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type risk_scores(risk_scoresSEXP);
    rcpp_result_gen = Rcpp::wrap(breslow_F(time, event, risk_scores));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_survivalisttoo_cox_gradient_at_F", (DL_FUNC) &_survivalisttoo_cox_gradient_at_F, 3},
    {"_survivalisttoo_breslow_F", (DL_FUNC) &_survivalisttoo_breslow_F, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_survivalisttoo(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
