# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

cox_gradient_at_F <- function(time, event, F_scores) {
    .Call(`_survivalisttoo_cox_gradient_at_F`, time, event, F_scores)
}

breslow_F <- function(time, event, risk_scores) {
    .Call(`_survivalisttoo_breslow_F`, time, event, risk_scores)
}

